export const PIPELINE_STEPS = {
  PDF_TEXT_EXTRACT: "PDF_TEXT_EXTRACT",
  OCR_EXTRACT: "OCR_EXTRACT",
  LLM_PARSE: "LLM_PARSE"
};

export const PIPELINE_STATUS = {
  UPLOADED: "UPLOADED",
  PROCESSING: "PROCESSING",
  DONE: "DONE",
  FAILED: "FAILED",
  RETRYING: "RETRYING"
};

export const EXTRACTION_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
};

export const EXTRACTION_METHOD = {
  PDF_TEXT: "PDF_TEXT",
  OCR: "OCR"
};

export const PARSING_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED"
};

export const SIGNALS = {
  DATE: "DATE",
  REGNO: "REGNO",
  AMOUNT: "AMOUNT",
  VAT: "VAT",
  DOC_TYPE: "DOC_TYPE"
};

export const EVENT_ACTIONS = {
  START: "START",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
};
